obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/


#ifdef VENDOR_EDIT /* LiYue@BSP.CHG.Basic, 2019/09/02, Add for charging */
obj-$(CONFIG_OPPO_CHARGER)	+= oppo/
#endif
