#
#Makefile for the touchscreen drivers.
#
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
obj-y += util_interface/
obj-y += touchpanel_common_driver.o touch.o
obj-y += Himax/
obj-y += Novatek/
