# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_DRM_PANEL_LVDS) += panel-lvds.o
obj-$(CONFIG_DRM_PANEL_SIMPLE) += panel-simple.o
obj-$(CONFIG_DRM_PANEL_INNOLUX_P079ZCA) += panel-innolux-p079zca.o
obj-$(CONFIG_DRM_PANEL_JDI_LT070ME05000) += panel-jdi-lt070me05000.o
obj-$(CONFIG_DRM_PANEL_LG_LG4573) += panel-lg-lg4573.o
obj-$(CONFIG_DRM_PANEL_PANASONIC_VVX10F034N00) += panel-panasonic-vvx10f034n00.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_LD9040) += panel-samsung-ld9040.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3HA2) += panel-samsung-s6e3ha2.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E8AA0) += panel-samsung-s6e8aa0.o
obj-$(CONFIG_DRM_PANEL_SHARP_LQ101R1SX01) += panel-sharp-lq101r1sx01.o
obj-$(CONFIG_DRM_PANEL_SHARP_LS043T1LE01) += panel-sharp-ls043t1le01.o
obj-$(CONFIG_DRM_PANEL_SITRONIX_ST7789V) += panel-sitronix-st7789v.o
obj-$(CONFIG_DRM_PANEL_AUO_U40073) += panel-auo-u40073.o
obj-$(CONFIG_DRM_PANEL_LG_U40073) += panel-lg-u40073.o
obj-$(CONFIG_DRM_PANEL_LG_0565G40108) += panel-lg-0565g40108.o
obj-$(CONFIG_DRM_PANEL_LG_0565G40108_CMD) += panel-lg-0565g40108-cmd.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_AMS601NN04_CMD) += panel-samsung-ams601nn04-cmd.o
obj-$(CONFIG_DRM_PANEL_NT35695B_AUO_VDO) += panel-nt35695b-auo-vdo.o
obj-$(CONFIG_DRM_PANEL_NT35695B_AUO_CMD) += panel-nt35695b-auo-cmd.o
obj-$(CONFIG_DRM_PANEL_AUO_HX83112B_VDO) += panel-auo-hx83112b-vdo.o
obj-$(CONFIG_DRM_PANEL_OTM1911A_AUO_VDO) += panel-otm1911a-auo-vdo.o
obj-$(CONFIG_DRM_PANEL_TRULY_TD4330_VDO) += panel-truly-td4330-vdo.o
obj-$(CONFIG_DRM_PANEL_TRULY_TD4330_CMD) += panel-truly-td4330-cmd.o
obj-$(CONFIG_DRM_PANEL_K6885V1_64_ALPHA_VDO_01) += panel-k6885v1-64-alpha-vdo-01.o
obj-$(CONFIG_DRM_PANEL_K6885V1_64_ALPHA_VDO_02) += panel-k6885v1-64-alpha-vdo-02.o
obj-$(CONFIG_DRM_PANEL_JDI_NT36672C_CPHY_VDO) += panel-jdi-nt36672c-cphy-vdo.o
obj-$(CONFIG_DRM_PANEL_TIANMA_NT36672C_CPHY_VDO) += panel-tianma-nt36672c-cphy-vdo.o
obj-$(CONFIG_DRM_PANEL_JDI_HX83112F_CPHY_VDO) += panel-jdi-hx83112f-cphy-vdo.o
obj-$(CONFIG_DRM_PANEL_TIANMA_120_NT36672C_CPHY_VDO) += panel-tianma-120-nt36672c-cphy-vdo.o
obj-$(CONFIG_DRM_PANEL_OPPO19040_SAMSUNG_ANA6705_1080P_DSI_CMD) += oppo19040_samsung_ana6705_1080p_dsi_cmd.o
obj-$(CONFIG_DRM_PANEL_ALPHA_TIANMA_NT36672C_CPHY_VDO) += panel-alpha-tianma-nt36672c-cphy-vdo.o
obj-$(CONFIG_DRM_PANEL_ALPHA_JDI_NT36672C_CPHY_VDO) += panel-alpha-jdi-nt36672c-cphy-vdo.o
obj-$(CONFIG_DRM_PANEL_K6873V1_64_ALPHA_VDO_01) += k6873v1_64_alpha/panel-k6873v1-64-alpha-vdo-01.o
obj-$(CONFIG_DRM_PANEL_K6873V1_64_ALPHA_VDO_02) += k6873v1_64_alpha/panel-k6873v1-64-alpha-vdo-02.o
obj-$(CONFIG_DRM_PANEL_HX_NT36682C_DPHY_VDO) += panel-hx-nt36682c-dphy-vdo.o
obj-$(CONFIG_DRM_PANEL_TIANMA_NT36672C_VDO_120HZ) += panel-tianma-nt36672c-vdo-120hz.o
obj-$(CONFIG_DRM_PANEL_TIANMA_NT36672C_VDO_144HZ) += panel-tianma-nt36672c-vdo-144hz.o
obj-$(CONFIG_DRM_PANEL_OPPO20001_TM_HX83112F_VDO) +=panel-oppo20001_hx83112f_fhdp_dsi_vdo_dphy.o
obj-$(CONFIG_DRM_PANEL_OPPO20001_TM_HX83112F_VDO_58) +=panel-oppo20001_hx83112f_fhdp_dsi_vdo_dphy_58.o
obj-$(CONFIG_DRM_PANEL_OPPO20001_JDI_NT36672C_VDO) += panel-oppo20001_nt36672c_fhdp_dsi_vdo_dphy.o
obj-$(CONFIG_DRM_PANEL_OPPO20051_JDI_NT36672C_VDO) += panel-oppo20051_nt36672c_fhdp_dsi_vdo_dphy_60.o
obj-$(CONFIG_DRM_PANEL_OPPO20075_SAMSUNG_DPHY_VDO) += panel-oppo20075_samsung_dsi_vdo_dphy.o
obj-$(CONFIG_DRM_PANEL_OPPO20001_TM_ILI7807S_VDO) += panel-oppo20001_ili7807s_fhdp_dsi_vdo_dphy.o
obj-$(CONFIG_DRM_PANEL_OPPO20041_TM_NT36672C_VDO) += panel-oppo20041_nt36672c_fhdp_dsi_vdo_dphy.o
#ifdef VENDOR_EDIT
#shangruofan@MM.LCD, 2020/04/17, add for change in US version
ifeq ($(TARGET_BUILD_VERSION),US)
ccflags-$(CONFIG_OPPO_420_SUPPORT) += -DOPPO_420_SUPPORT
endif
#endif VENDOR_EDIT

obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_01) += k6853v1_64_alpha/panel-k6853v1-64-alpha-vdo-01.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_02) += k6853v1_64_alpha/panel-k6853v1-64-alpha-vdo-02.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_02) += k6853v1_64_alpha/panel-k6853v1-64-alpha-vdo-03.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_0021) += k6853v1_64_alpha/panel-k6853v1_64_alpha_02_vdo_60hz.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_0022) += k6853v1_64_alpha/panel-k6853v1_64_alpha_02_vdo_90hz.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_0020) += k6853v1_64_alpha/panel-k6853v1_64_alpha_02_vdo_120hz.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_0031) += k6853v1_64_alpha/panel-k6853v1_64_alpha_03_vdo_60hz.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_0032) += k6853v1_64_alpha/panel-k6853v1_64_alpha_03_vdo_90hz.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_VDO_0030) += k6853v1_64_alpha/panel-k6853v1_64_alpha_03_vdo_120hz.o
obj-$(CONFIG_DRM_PANEL_K6853V1_64_ALPHA_AOD_VDO_01) += k6853v1_64_alpha/panel-k6853v1-64-alpha-aod-vdo-01.o
obj-$(CONFIG_DRM_PANEL_NT36672A_RT4801_VDO) += panel-nt36672a-rt4801-vdo.o
obj-$(CONFIG_DRM_PANEL_SC_NT36672C_VDO_120HZ) += panel-sc-nt36672c-vdo-120hz.o
obj-$(CONFIG_DRM_PANEL_SC_NT36672C_VDO_90HZ) += panel-sc-nt36672c-vdo-90hz.o
obj-$(CONFIG_DRM_PANEL_SC_NT36672C_VDO_60HZ) += panel-sc-nt36672c-vdo-60hz.o

