#ifdef VENDOR_EDIT
#/* Hank.liu@TECH.PLAT.Storage, 2020-2-18, add oppo iomonitor driver*/
obj-$(CONFIG_OPPO_IOMONITOR)	+=	console.o
obj-$(CONFIG_OPPO_IOMONITOR)	+=  oppo_iomonitor.o
obj-$(CONFIG_OPPO_IOMONITOR)	+=	iotrace.o
obj-$(CONFIG_OPPO_IOMONITOR)	+=  oppo_uid_status.o
#endif /* VENDOR_EDIT */
