#
#Makefile for the touchscreen drivers.
#
#Each configuration option enables a list of files.
subdir-ccflags-y += -I$(srctree)/drivers/input/touchscreen/k6873v1_64_alpha/
obj-y += himax_common.o
obj-y += hx83112f_noflash/
